import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import { Button, Flex } from "@chakra-ui/react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Flex m={3} justify="flex-end" gap={2}>
            <Link href="/liturgy">
              <Button>Ogłoszenia parafialne</Button>
            </Link>
            <Link href="/koleda">
              <Button>Kolęda</Button>
            </Link>
          </Flex>
          {children}
        </Providers>
      </body>
    </html>
  );
}
